name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build -- --base=./

      - name: Store website
        uses: actions/upload-artifact@v4
        with:
          name: todo
          path: dist/

  delivery:
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Load website
        uses: actions/download-artifact@v4
        with:
          name: todo
          path: dist/

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ vars.SUBDOMAIN }}/test/
          local-dir: dist/

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx testcafe chrome:headless test/e2e/* --browser-init-timeout 60000

  deployment:
    needs: delivery
    runs-on: ubuntu-latest

    steps:
      - name: Load website
        uses: actions/download-artifact@v4
        with:
          name: todo
          path: dist/

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ vars.SUBDOMAIN }}/live/
          local-dir: dist/